version: "3"

services:
  database:
    container_name: iot-platform-db
    image: mongo:4.4.1
    restart: always
    volumes:
      - mongo:/data/db
    ports:
      - 27017:27017

  message-queue:
    container_name: iot-platform-message-queue
    image: rabbitmq:3-management
    hostname: rabbit
    restart: always
    environment: 
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER:-admin}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS:-admin}
    ports:
      - 15672:15672
      - 5672:5672

  api:
    container_name: iot-platform-api
    build: api
    image: iot-platform-api
    restart: always
    environment:
      - MONGO_URL=mongodb://database:27017/iot-platform
      - RABBIT_URL=amqp://admin:admin@message-queue:5672
    volumes:
      - .:/usr/src/app
      - /usr/src/app/api/node_modules
    ports:
      - 8080:8080
    depends_on:
      - database
      - message-queue

  web:
    container_name: iot-platform-web
    build: web
    image: iot-platform-web
    restart: always
    volumes:
      - .:/usr/src/app
      - /usr/src/app/web/node_modules
    ports: 
      - 4200:4200
    depends_on:
      - api

volumes:
  mongo:
