version: "3"

services:
  database:
    container_name: iot-platform-db
    image: mongo:4.4.1
    restart: always
    volumes:
      - mongo:/data/db
    ports:
      - 27017:27017

  api:
    container_name: iot-platform-api
    build: api
    image: iot-platform-api
    restart: always
    environment:
      - MONGO_URL=mongodb://database:27017/iot-platform
    volumes:
      - ./api:/usr/src/app/api
      - /usr/src/app/api/node_modules
    ports:
      - 8080:8080
    depends_on:
      - database

volumes:
  mongo:
